import React, { useState, useMemo } from 'react';
import { Personality, Memory, Message, AIConfig } from '../App';
import { generateUniqueMemoryId, deduplicateMemories } from '../utils/memory-deduplicator';
import { Button } from './ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/card';
import { Label } from './ui/label';
import { Input } from './ui/input';
import { Textarea } from './ui/textarea';
import { Badge } from './ui/badge';
import { ScrollArea } from './ui/scroll-area';
import { Avatar, AvatarFallback } from './ui/avatar';
import { SafeAvatar } from './SafeAvatar';
import { toast } from 'sonner@2.0.3';
import { Plus, Trash2, Edit2, Save, X, Brain, Star, AlertCircle, Clock, Infinity, Search, BarChart3, Sparkles, Users } from 'lucide-react';
import { extractMemoriesFromConversation } from '../utils/gemini-service';
import { getActualModel } from '../utils/get-actual-model';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from './ui/alert-dialog';
import {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from './ui/tabs';

interface MemoryManagerProps {
  personality: Personality;
  personalities: Personality[];
  setPersonalities: (personalities: Personality[]) => void;
  messages: Message[];
  config: AIConfig;
  chats: any[]; // 聊天记录列表
}

export function MemoryManager({
  personality: initialPersonality,
  personalities,
  setPersonalities,
  messages: initialMessages,
  config,
  chats,
}: MemoryManagerProps) {
  // 当前选中的女友ID
  const [selectedPersonalityId, setSelectedPersonalityId] = useState(initialPersonality.id);
  
  // 根据选中ID获取对应的女友和消息
  const personality = personalities.find(p => p.id === selectedPersonalityId) || initialPersonality;
  const currentChat = chats?.find(c => c.personalityId === selectedPersonalityId);
  const messages = currentChat?.messages || [];
  
  const [editingId, setEditingId] = useState<string | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [newMemory, setNewMemory] = useState<{
    content: string;
    memoryType: 'short-term' | 'long-term';
    importance: 'low' | 'medium' | 'high';
    tags: string;
  }>({
    content: '',
    memoryType: 'short-term',
    importance: 'medium',
    tags: '',
  });
  const [isGenerating, setIsGenerating] = useState(false);
  const [isImporting, setIsImporting] = useState(false);
  const [editStates, setEditStates] = useState<Record<string, {
    content: string;
    importance: 'low' | 'medium' | 'high';
    tags: string;
  }>>({});

  // 去重：确保ID唯一
  const uniqueMemories = useMemo(() => {
    const rawMemories = personality.memories || [];
    return deduplicateMemories(rawMemories);
  }, [personality.memories]);

  const memories = uniqueMemories;

  // 分类记忆
  const { shortTermMemories, longTermMemories } = useMemo(() => {
    const short = memories.filter(m => m.memoryType === 'short-term');
    const long = memories.filter(m => m.memoryType === 'long-term');
    return { shortTermMemories: short, longTermMemories: long };
  }, [memories]);

  // 搜索过滤
  const filterMemories = (mems: Memory[]) => {
    if (!searchQuery.trim()) return mems;
    const query = searchQuery.toLowerCase();
    return mems.filter(m =>
      m.content.toLowerCase().includes(query) ||
      m.tags.some(tag => tag.toLowerCase().includes(query))
    );
  };

  const filteredShortTerm = filterMemories(shortTermMemories);
  const filteredLongTerm = filterMemories(longTermMemories);

  // 统计信息
  const autoGeneratedCount = memories.filter(m => m.autoGenerated).length;
  const manualCount = memories.length - autoGeneratedCount;
  const highImportanceCount = memories.filter(m => m.importance === 'high').length;

  const updatePersonalityMemories = (newMemories: Memory[]) => {
    setPersonalities(
      personalities.map(p =>
        p.id === personality.id ? { ...p, memories: newMemories } : p
      )
    );
  };

  const handleAddMemory = () => {
    if (!newMemory.content.trim()) {
      toast.error('请输入记忆内容');
      return;
    }

    const memory: Memory = {
      id: `memory-${Date.now()}`,
      content: newMemory.content.trim(),
      memoryType: newMemory.memoryType,
      importance: newMemory.importance,
      timestamp: Date.now(),
      tags: newMemory.tags.split(',').map(t => t.trim()).filter(Boolean),
      autoGenerated: false,
    };

    updatePersonalityMemories([...memories, memory]);

    setNewMemory({
      content: '',
      memoryType: 'short-term',
      importance: 'medium',
      tags: '',
    });

    toast.success('记忆已添加');
  };

  const handleDeleteMemory = (id: string) => {
    const memory = memories.find(m => m.id === id);
    
    // 长时记忆需要二次确认
    if (memory?.memoryType === 'long-term') {
      // 由AlertDialog处理确认
      return;
    }

    // 短时记忆直接删除
    updatePersonalityMemories(memories.filter(m => m.id !== id));
    toast.success('短时记忆已删除');
  };

  const confirmDeleteLongTermMemory = (id: string) => {
    updatePersonalityMemories(memories.filter(m => m.id !== id));
    toast.success('长时记忆已删除');
  };

  const handleEditMemory = (id: string) => {
    setEditingId(id);
  };

  const handleSaveEdit = (id: string, updates: Partial<Memory>) => {
    updatePersonalityMemories(
      memories.map(m => (m.id === id ? { ...m, ...updates } : m))
    );
    setEditingId(null);
    toast.success('记忆已更新');
  };

  const handleClearShortTermMemories = () => {
    updatePersonalityMemories(memories.filter(m => m.memoryType === 'long-term'));
    toast.success('所有短时记忆已清除');
  };

  // AI自动分析聊天记录生成记忆
  const handleGenerateMemoriesFromChat = async () => {
    if (!config.geminiApiKey) {
      toast.error('请先在配置面板中设置Gemini API Key');
      return;
    }

    if (messages.length === 0) {
      toast.error('当前没有聊天记录可分析');
      return;
    }

    setIsGenerating(true);
    console.log('🧠 开始AI分析聊天记录，生成记忆...');
    console.log(`  - 聊天记录数: ${messages.length}`);
    console.log(`  - 现有记忆数: ${memories.length}`);

    try {
      const model = getActualModel(config);
      console.log(`  - 使用模型: ${model}`);

      const memoryResult = await extractMemoriesFromConversation(
        messages,
        config.geminiApiKey,
        model
      );

      if (!memoryResult.memories || memoryResult.memories.length === 0) {
        toast.error('AI未能从对话中提取有价值的记忆');
        console.warn('⚠️ AI未返回任何记忆');
        setIsGenerating(false);
        return;
      }

      console.log(`✅ AI成功提取 ${memoryResult.memories.length} 条记忆`);

      // 格式化时间
      const formatTime = (timestamp: number) => {
        const date = new Date(timestamp);
        return date.toLocaleString('zh-CN', {
          year: 'numeric',
          month: '2-digit',
          day: '2-digit',
          hour: '2-digit',
          minute: '2-digit',
        });
      };

      // 将AI提取的记忆转换为统一格式
      const newMemories = memoryResult.memories.map((mem, index) => ({
        id: `ai-memory-${Date.now()}-${index}`,
        personalityId: personality.id,
        type: 'chat' as const,
        content: mem.content,
        memoryType: mem.memoryType,
        importance: mem.importance,
        timestamp: Date.now(),
        tags: [...mem.tags, '🤖 AI生成', '💬 聊天分析'],
        autoGenerated: true,
        metadata: {
          messageCount: messages.length,
          dateRange: messages.length > 0 
            ? `${formatTime(messages[0].timestamp)} - ${formatTime(messages[messages.length - 1].timestamp)}`
            : '无',
          model: model,
        },
      }));

      console.log('📝 新生成的记忆:', newMemories);

      // 添加到现有记忆
      const updatedMemories = [...memories, ...newMemories];
      updatePersonalityMemories(updatedMemories);
      
      toast.success(`✨ AI成功生成 ${newMemories.length} 条记忆！`, {
        description: `已从 ${messages.length} 条聊天记录中提取关键信息`,
      });
      
      console.log(`✅ 记忆已更新，总数: ${updatedMemories.length}`);
    } catch (error) {
      console.error('❌ AI生成记忆失败:', {
        error,
        message: (error as Error).message,
        stack: (error as Error).stack,
        messagesCount: messages.length,
        apiKeySet: !!config.geminiApiKey,
      });
      
      const errorMessage = (error as Error).message || '未知错误';
      if (errorMessage.includes('API key')) {
        toast.error('API密钥错误', {
          description: '请检查Gemini API Key设置是否正确',
        });
      } else if (errorMessage.includes('quota')) {
        toast.error('API配额已用完', {
          description: '请检查账户余额或稍后再试',
        });
      } else if (errorMessage.includes('network')) {
        toast.error('网络错误', {
          description: '请检查网络连接后重试',
        });
      } else {
        toast.error(`生成记忆失败：${errorMessage}`, {
          description: '请查看控制台了解详细错误信息',
        });
      }
    } finally {
      setIsGenerating(false);
    }
  };

  // 强制导入所有聊天记录到记忆库（原始格式，不经过AI分析）
  const handleImportAllChatMessages = () => {
    if (messages.length === 0) {
      toast.error('当前没有聊天记录可导入');
      return;
    }

    setIsImporting(true);
    console.log('📥 开始导入所有聊天记录到记忆库...');
    console.log(`  - 聊天记录数: ${messages.length}`);
    console.log(`  - 现有记忆数: ${memories.length}`);

    try {
      // 格式化时间
      const formatTime = (timestamp: number) => {
        const date = new Date(timestamp);
        return date.toLocaleString('zh-CN', {
          year: 'numeric',
          month: '2-digit',
          day: '2-digit',
          hour: '2-digit',
          minute: '2-digit',
          second: '2-digit',
        });
      };

      // 将所有聊天消息转换为记忆格式
      const importTimestamp = Date.now(); // 使用导入时的时间戳确保唯一性
      const importedMemories = messages.map((msg) => {
        const isUser = msg.role === 'user';
        const roleLabel = isUser ? '👤 用户' : `🤖 ${personality.name}`;
        
        return {
          id: generateUniqueMemoryId('imported-msg'),
          personalityId: personality.id,
          type: 'chat' as const,
          content: `${roleLabel}: ${msg.content}`,
          memoryType: 'short-term' as const, // 默认作为短时记忆
          importance: 'low' as const, // 原始记录默认为低重要性
          timestamp: msg.timestamp,
          tags: [
            '📥 强制导入',
            '💬 原始对话',
            isUser ? '用户消息' : 'AI回复',
            formatTime(msg.timestamp).split(' ')[0], // 添加日期标签
          ],
          autoGenerated: false,
          metadata: {
            originalRole: msg.role,
            originalTimestamp: msg.timestamp,
            importedAt: importTimestamp,
          },
        };
      });

      console.log(`📝 已转换 ${importedMemories.length} 条消息为记忆格式`);

      // 添加到现有记忆
      const updatedMemories = [...memories, ...importedMemories];
      updatePersonalityMemories(updatedMemories);
      
      toast.success(`✅ 成功导入 ${importedMemories.length} 条聊天记录！`, {
        description: `所有对话已保存为记忆，现在可以使用"AI智能总结"进行分析`,
        duration: 5000,
      });
      
      console.log(`✅ 导入完成，总记忆数: ${updatedMemories.length}`);
      console.log('💡 提示：现在可以点击"AI智能总结"按钮对这些记忆进行智能分析');
    } catch (error) {
      console.error('❌ 导入聊天记录失败:', error);
      toast.error('导入失败', {
        description: (error as Error).message || '未知错误',
      });
    } finally {
      setIsImporting(false);
    }
  };

  const getImportanceIcon = (importance: 'low' | 'medium' | 'high') => {
    switch (importance) {
      case 'high':
        return <Star className="w-3 h-3" />;
      case 'medium':
        return <AlertCircle className="w-3 h-3" />;
      case 'low':
        return <Clock className="w-3 h-3" />;
    }
  };

  const getImportanceColor = (importance: 'low' | 'medium' | 'high') => {
    switch (importance) {
      case 'high':
        return 'bg-red-500/10 text-red-700 dark:text-red-400 border-red-500/20';
      case 'medium':
        return 'bg-yellow-500/10 text-yellow-700 dark:text-yellow-400 border-yellow-500/20';
      case 'low':
        return 'bg-muted text-muted-foreground border-border';
    }
  };

  const renderMemoryCard = (memory: Memory) => {
    const isEditing = editingId === memory.id;
    
    // 初始化编辑状态
    if (isEditing && !editStates[memory.id]) {
      setEditStates({
        ...editStates,
        [memory.id]: {
          content: memory.content,
          importance: memory.importance,
          tags: memory.tags.join(', '),
        },
      });
    }
    
    const editState = editStates[memory.id] || {
      content: memory.content,
      importance: memory.importance,
      tags: memory.tags.join(', '),
    };

    return (
      <Card key={memory.id} className="relative active:shadow-lg transition-shadow">
        <CardContent className="pt-4 space-y-3 touch-pan-y">
          {/* 记忆类型标识 */}
          <div className="flex items-center justify-between">
            <Badge
              variant="outline"
              className={
                memory.memoryType === 'long-term'
                  ? 'bg-purple-100 text-purple-800 border-purple-200'
                  : 'bg-blue-100 text-blue-800 border-blue-200'
              }
            >
              {memory.memoryType === 'long-term' ? (
                <>
                  <Infinity className="w-3 h-3 mr-1" />
                  长时记忆
                </>
              ) : (
                <>
                  <Clock className="w-3 h-3 mr-1" />
                  短时记忆
                </>
              )}
            </Badge>

            {memory.autoGenerated && (
              <Badge variant="outline" className="bg-green-100 text-green-800 border-green-200 text-xs">
                <Brain className="w-3 h-3 mr-1" />
                AI生成
              </Badge>
            )}
          </div>

          {/* 记忆内容 */}
          {isEditing ? (
            <Textarea
              value={editState.content}
              onChange={(e) => setEditStates({
                ...editStates,
                [memory.id]: { ...editState, content: e.target.value }
              })}
              className="min-h-[80px]"
              placeholder="记忆内容"
            />
          ) : (
            <p className="text-sm leading-relaxed">{memory.content}</p>
          )}

          {/* 重要性和标签 */}
          <div className="flex flex-wrap gap-2 items-center">
            {isEditing ? (
              <select
                value={editState.importance}
                onChange={(e) => setEditStates({
                  ...editStates,
                  [memory.id]: { ...editState, importance: e.target.value as 'low' | 'medium' | 'high' }
                })}
                className="text-xs border border-input rounded px-2 py-1 bg-background text-foreground"
              >
                <option value="high">⭐ 重要</option>
                <option value="medium">📍 一般</option>
                <option value="low">📝 普通</option>
              </select>
            ) : (
              <Badge variant="outline" className={getImportanceColor(memory.importance)}>
                {getImportanceIcon(memory.importance)}
                <span className="ml-1">
                  {memory.importance === 'high' ? '重要' : memory.importance === 'medium' ? '一般' : '普通'}
                </span>
              </Badge>
            )}

            {isEditing ? (
              <Input
                value={editState.tags}
                onChange={(e) => setEditStates({
                  ...editStates,
                  [memory.id]: { ...editState, tags: e.target.value }
                })}
                className="text-xs h-7 flex-1"
                placeholder="标签（逗号分隔）"
              />
            ) : (
              memory.tags.map((tag, idx) => (
                <Badge key={idx} variant="outline" className="text-xs">
                  {tag}
                </Badge>
              ))
            )}
          </div>

          {/* 时间戳 */}
          <p className="text-xs text-gray-400">
            {new Date(memory.timestamp).toLocaleString('zh-CN')}
          </p>

          {/* 操作按钮 */}
          <div className="flex gap-2 pt-2">
            {isEditing ? (
              <>
                <Button
                  size="sm"
                  onClick={() => {
                    handleSaveEdit(memory.id, {
                      content: editState.content,
                      importance: editState.importance,
                      tags: editState.tags.split(',').map(t => t.trim()).filter(Boolean),
                    });
                    // 清除编辑状态
                    const newEditStates = { ...editStates };
                    delete newEditStates[memory.id];
                    setEditStates(newEditStates);
                  }}
                  className="bg-green-500 hover:bg-green-600 touch-manipulation min-h-[40px]"
                >
                  <Save className="w-3 h-3 mr-1" />
                  保存
                </Button>
                <Button 
                  size="sm" 
                  variant="outline" 
                  onClick={() => {
                    setEditingId(null);
                    // 清除编辑状态
                    const newEditStates = { ...editStates };
                    delete newEditStates[memory.id];
                    setEditStates(newEditStates);
                  }}
                  className="touch-manipulation min-h-[40px]"
                >
                  <X className="w-3 h-3 mr-1" />
                  取消
                </Button>
              </>
            ) : (
              <>
                <Button 
                  size="sm" 
                  variant="outline" 
                  onClick={() => handleEditMemory(memory.id)}
                  className="touch-manipulation min-h-[40px]"
                >
                  <Edit2 className="w-3 h-3 mr-1" />
                  编辑
                </Button>
                {memory.memoryType === 'long-term' ? (
                  <AlertDialog>
                    <AlertDialogTrigger asChild>
                      <Button 
                        size="sm" 
                        variant="outline" 
                        className="text-red-600 hover:text-red-700 touch-manipulation min-h-[40px]"
                      >
                        <Trash2 className="w-3 h-3 mr-1" />
                        删除
                      </Button>
                    </AlertDialogTrigger>
                    <AlertDialogContent className="w-[90vw] max-w-md">
                      <AlertDialogHeader>
                        <AlertDialogTitle>确认删除长时记忆？</AlertDialogTitle>
                        <AlertDialogDescription>
                          这是一条长时记忆，删除后将永久消失且无法恢复。你确定要删除吗？
                        </AlertDialogDescription>
                      </AlertDialogHeader>
                      <AlertDialogFooter className="flex-col sm:flex-row gap-2">
                        <AlertDialogCancel className="touch-manipulation min-h-[44px]">取消</AlertDialogCancel>
                        <AlertDialogAction
                          onClick={() => confirmDeleteLongTermMemory(memory.id)}
                          className="bg-red-500 hover:bg-red-600 touch-manipulation min-h-[44px]"
                        >
                          确认删除
                        </AlertDialogAction>
                      </AlertDialogFooter>
                    </AlertDialogContent>
                  </AlertDialog>
                ) : (
                  <Button
                    size="sm"
                    variant="outline"
                    className="text-red-600 hover:text-red-700 touch-manipulation min-h-[40px]"
                    onClick={() => handleDeleteMemory(memory.id)}
                  >
                    <Trash2 className="w-3 h-3 mr-1" />
                    删除
                  </Button>
                )}
              </>
            )}
          </div>
        </CardContent>
      </Card>
    );
  };

  return (
    <div className="h-full flex flex-col md:flex-row gap-4">
      {/* 左侧：女友选择列表 */}
      <div className="md:w-64 flex-shrink-0">
        <Card className="h-full">
          <CardHeader className="pb-3">
            <CardTitle className="text-base flex items-center gap-2">
              <Users className="w-4 h-4" />
              选择女友
            </CardTitle>
            <CardDescription className="text-xs">
              点击切换不同女友的记忆库
            </CardDescription>
          </CardHeader>
          <CardContent className="p-0">
            <div className="space-y-1 max-h-[60vh] overflow-y-auto">
              {personalities.map((p) => {
                const isSelected = p.id === selectedPersonalityId;
                const pMemories = p.memories || [];
                return (
                  <button
                    key={p.id}
                    onClick={() => setSelectedPersonalityId(p.id)}
                    className={`w-full px-3 py-3 flex items-center gap-3 hover:bg-accent transition-colors text-left ${
                      isSelected ? 'bg-accent border-l-4 border-purple-500' : ''
                    }`}
                  >
                    <SafeAvatar
                      src={p.avatarUrl}
                      fallback={p.name?.[0] || '?'}
                      className="w-10 h-10 flex-shrink-0"
                      fallbackClassName="bg-gradient-to-br from-green-400 to-teal-500 text-white"
                    />
                    <div className="flex-1 min-w-0">
                      <p className={`truncate text-sm ${isSelected ? 'font-semibold' : ''}`}>
                        {p.name}
                      </p>
                      <p className="text-xs text-muted-foreground">
                        {pMemories.length} 条记忆
                      </p>
                    </div>
                  </button>
                );
              })}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* 右侧：记忆管理主内容 */}
      <div className="flex-1 flex flex-col space-y-4 min-w-0 overflow-hidden">
        {/* 标题和统计 */}
        <div className="flex items-center justify-between flex-shrink-0">
          <div className="min-w-0">
            <h2 className="flex items-center gap-2">
              <Brain className="w-6 h-6 text-purple-600 flex-shrink-0" />
              <span className="truncate">{personality.name} 的记忆库</span>
            </h2>
            <p className="text-sm text-muted-foreground mt-1">
              长时记忆 {longTermMemories.length} 条（永久保存） • 短时记忆 {shortTermMemories.length} 条（可自动清理）
            </p>
            <p className="text-xs text-muted-foreground mt-1 hidden lg:block">
              💡 AI每隔5条消息自动总结记忆，长时记忆永不遗忘，短时记忆超过7天或30条后自动清理
            </p>
          </div>
        </div>

      {/* 统计卡片 */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3 flex-shrink-0">
        <Card className="p-3">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-full bg-purple-100 dark:bg-purple-900/20 flex items-center justify-center">
              <Brain className="w-4 h-4 text-purple-600 dark:text-purple-400" />
            </div>
            <div>
              <p className="text-xs text-gray-500">总记忆</p>
              <p className="text-lg font-semibold">{memories.length}</p>
            </div>
          </div>
        </Card>
        <Card className="p-3">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-full bg-green-100 dark:bg-green-900/20 flex items-center justify-center">
              <Sparkles className="w-4 h-4 text-green-600 dark:text-green-400" />
            </div>
            <div>
              <p className="text-xs text-gray-500">AI生成</p>
              <p className="text-lg font-semibold">{autoGeneratedCount}</p>
            </div>
          </div>
        </Card>
        <Card className="p-3">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-full bg-blue-100 dark:bg-blue-900/20 flex items-center justify-center">
              <Edit2 className="w-4 h-4 text-blue-600 dark:text-blue-400" />
            </div>
            <div>
              <p className="text-xs text-gray-500">手动添加</p>
              <p className="text-lg font-semibold">{manualCount}</p>
            </div>
          </div>
        </Card>
        <Card className="p-3">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-full bg-red-100 dark:bg-red-900/20 flex items-center justify-center">
              <Star className="w-4 h-4 text-red-600 dark:text-red-400" />
            </div>
            <div>
              <p className="text-xs text-gray-500">重要记忆</p>
              <p className="text-lg font-semibold">{highImportanceCount}</p>
            </div>
          </div>
        </Card>
      </div>

      {/* 搜索框 */}
      <div className="relative">
        <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none" />
        <Input
          placeholder="搜索记忆内容或标签..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="pl-10 touch-manipulation min-h-[44px] md:min-h-[36px]"
        />
      </div>

      {/* 添加新记忆 */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">添加新记忆</CardTitle>
          <CardDescription>
            手动添加记忆，或等待AI自动提取（每发送5条消息自动触发）
            <br />
            💡 长时记忆：重要信息永久保存 | 短时记忆：临时信息定期清理
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          <div>
            <Label>记忆内容</Label>
            <Textarea
              placeholder="输入记忆内容..."
              value={newMemory.content}
              onChange={(e) => setNewMemory({ ...newMemory, content: e.target.value })}
              className="min-h-[80px]"
            />
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <Label>记忆类型</Label>
              <select
                value={newMemory.memoryType}
                onChange={(e) => setNewMemory({ ...newMemory, memoryType: e.target.value as any })}
                className="w-full border rounded-md px-3 py-2 text-sm"
              >
                <option value="short-term">⏰ 短时记忆</option>
                <option value="long-term">♾️ 长时记忆</option>
              </select>
            </div>

            <div>
              <Label>重要性</Label>
              <select
                value={newMemory.importance}
                onChange={(e) => setNewMemory({ ...newMemory, importance: e.target.value as any })}
                className="w-full border rounded-md px-3 py-2 text-sm"
              >
                <option value="high">⭐ 重要</option>
                <option value="medium">📍 一般</option>
                <option value="low">📝 普通</option>
              </select>
            </div>
          </div>

          <div>
            <Label>标签（可选，用逗号分隔）</Label>
            <Input
              placeholder="例如：约会, 喜好, 承诺"
              value={newMemory.tags}
              onChange={(e) => setNewMemory({ ...newMemory, tags: e.target.value })}
            />
          </div>

          {/* 操作按钮 */}
          <div className="space-y-3">
            {/* 第一行：手动添加 + AI智能提取 */}
            <div className="grid grid-cols-2 gap-3">
              <Button 
                onClick={handleAddMemory} 
                className="bg-green-500 hover:bg-green-600 touch-manipulation min-h-[44px]"
              >
                <Plus className="w-4 h-4 md:mr-2" />
                <span className="hidden md:inline">手动添加</span>
              </Button>
              <Button 
                onClick={handleGenerateMemoriesFromChat}
                disabled={isGenerating || messages.length === 0}
                className="bg-purple-500 hover:bg-purple-600 touch-manipulation min-h-[44px]"
              >
                {isGenerating ? (
                  <>
                    <div className="w-4 h-4 mr-2 border-2 border-white border-t-transparent rounded-full animate-spin" />
                    <span className="hidden sm:inline">AI分析中...</span>
                    <span className="sm:hidden">分析中</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="w-4 h-4 md:mr-2" />
                    <span className="hidden sm:inline">AI智能总结</span>
                    <span className="sm:hidden">AI总结</span>
                  </>
                )}
              </Button>
            </div>

            {/* 第二行：强制导入聊天记录 */}
            <Button 
              onClick={handleImportAllChatMessages}
              disabled={isImporting || messages.length === 0}
              variant="outline"
              className="w-full border-2 border-blue-500 text-blue-600 hover:bg-blue-50 dark:hover:bg-blue-950 touch-manipulation min-h-[44px] text-sm md:text-base"
            >
              {isImporting ? (
                <>
                  <div className="w-4 h-4 mr-2 border-2 border-blue-600 border-t-transparent rounded-full animate-spin" />
                  <span className="hidden sm:inline">正在导入...</span>
                  <span className="sm:hidden">导入中</span>
                </>
              ) : (
                <>
                  📥 <span className="hidden sm:inline">强制导入所有聊天记录 ({messages.length} 条)</span>
                  <span className="sm:inline hidden">导入聊天 ({messages.length})</span>
                </>
              )}
            </Button>
          </div>
          
          {/* 使用说明 */}
          {messages.length === 0 ? (
            <div className="bg-gray-50 dark:bg-gray-900 rounded-lg p-3 text-xs text-gray-600 dark:text-gray-400">
              <p>💡 当前没有聊天记录，请先与 {personality.name} 聊天</p>
            </div>
          ) : (
            <div className="bg-blue-50 dark:bg-blue-950 rounded-lg p-3 space-y-2">
              <p className="text-xs text-blue-700 dark:text-blue-300">
                📊 当前有 <span className="font-semibold">{messages.length}</span> 条聊天记录可处理
              </p>
              <div className="text-xs text-blue-600 dark:text-blue-400 space-y-1">
                <p>• <span className="font-semibold">AI智能总结</span>：AI分析对话，提取关键信息（推荐）</p>
                <p>• <span className="font-semibold">强制导入</span>：原样保存所有对话，然后再总结</p>
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* 记忆列表 - 分标签页 */}
      <Tabs defaultValue="long-term" className="flex-1 flex flex-col min-h-0">
        <TabsList className="grid w-full grid-cols-2 h-auto">
          <TabsTrigger value="long-term" className="touch-manipulation min-h-[44px] md:min-h-[36px] text-xs md:text-sm">
            <Infinity className="w-4 h-4 md:mr-2 flex-shrink-0" />
            <span className="hidden sm:inline ml-1">长时记忆 ({filteredLongTerm.length})</span>
            <span className="sm:hidden ml-1">长时 ({filteredLongTerm.length})</span>
          </TabsTrigger>
          <TabsTrigger value="short-term" className="touch-manipulation min-h-[44px] md:min-h-[36px] text-xs md:text-sm">
            <Clock className="w-4 h-4 md:mr-2 flex-shrink-0" />
            <span className="hidden sm:inline ml-1">短时记忆 ({filteredShortTerm.length})</span>
            <span className="sm:hidden ml-1">短时 ({filteredShortTerm.length})</span>
          </TabsTrigger>
        </TabsList>

        <TabsContent value="long-term" className="flex-1 min-h-0">
          <ScrollArea className="h-[500px] pr-2 md:pr-4 overscroll-contain" style={{ WebkitOverflowScrolling: 'touch' }}>
            <div className="space-y-3">
              {filteredLongTerm.length === 0 ? (
                <Card>
                  <CardContent className="pt-6 text-center text-gray-500">
                    <Brain className="w-12 h-12 mx-auto mb-2 text-gray-300" />
                    <p>暂无长时记忆</p>
                    <p className="text-xs mt-1">
                      AI会自动识别重要对话并保存为长时记忆
                      <br />
                      长时记忆永久保存，绝不遗忘
                    </p>
                  </CardContent>
                </Card>
              ) : (
                filteredLongTerm
                  .sort((a, b) => {
                    // 按重要性和时间排序
                    const importanceOrder = { high: 3, medium: 2, low: 1 };
                    if (importanceOrder[a.importance] !== importanceOrder[b.importance]) {
                      return importanceOrder[b.importance] - importanceOrder[a.importance];
                    }
                    return b.timestamp - a.timestamp;
                  })
                  .map(renderMemoryCard)
              )}
            </div>
          </ScrollArea>
        </TabsContent>

        <TabsContent value="short-term" className="flex-1 min-h-0">
          <div className="mb-3">
            <AlertDialog>
              <AlertDialogTrigger asChild>
                <Button 
                  variant="outline" 
                  size="sm" 
                  className="text-red-600 hover:text-red-700 touch-manipulation min-h-[40px]"
                >
                  <Trash2 className="w-3 h-3 mr-2" />
                  清除所有短时记忆
                </Button>
              </AlertDialogTrigger>
              <AlertDialogContent className="w-[90vw] max-w-md">
                <AlertDialogHeader>
                  <AlertDialogTitle>确认清除所有短时记忆？</AlertDialogTitle>
                  <AlertDialogDescription>
                    这将删除所有短时记忆，但长时记忆会保留。此操作无法撤销。
                  </AlertDialogDescription>
                </AlertDialogHeader>
                <AlertDialogFooter className="flex-col sm:flex-row gap-2">
                  <AlertDialogCancel className="touch-manipulation min-h-[44px]">取消</AlertDialogCancel>
                  <AlertDialogAction
                    onClick={handleClearShortTermMemories}
                    className="bg-red-500 hover:bg-red-600 touch-manipulation min-h-[44px]"
                  >
                    确认清除
                  </AlertDialogAction>
                </AlertDialogFooter>
              </AlertDialogContent>
            </AlertDialog>
          </div>

          <ScrollArea className="h-[460px] pr-2 md:pr-4 overscroll-contain" style={{ WebkitOverflowScrolling: 'touch' }}>
            <div className="space-y-3 touch-pan-y">
              {filteredShortTerm.length === 0 ? (
                <Card>
                  <CardContent className="pt-6 text-center text-gray-500">
                    <Clock className="w-12 h-12 mx-auto mb-2 text-gray-300" />
                    <p>暂无短时记忆</p>
                    <p className="text-xs mt-1">
                      AI会自动记录临时性的对话内容
                      <br />
                      短时记忆超过7天或30条后自动清理
                    </p>
                  </CardContent>
                </Card>
              ) : (
                filteredShortTerm
                  .sort((a, b) => b.timestamp - a.timestamp)
                  .map(renderMemoryCard)
              )}
            </div>
          </ScrollArea>
        </TabsContent>
      </Tabs>
      </div>
    </div>
  );
}
