import React, { useState } from 'react';
import { Memory, Personality, Message, AIConfig } from '../App';
import { generateUniqueMemoryId, deduplicateMemories } from '../utils/memory-deduplicator';
import { Button } from './ui/button';
import { Textarea } from './ui/textarea';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { Card } from './ui/card';
import { Badge } from './ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from './ui/tabs';
import { toast } from 'sonner@2.0.3';
import {
  Brain,
  MessageSquare,
  Clock,
  Trash2,
  Edit,
  Plus,
  Save,
  X,
  Sparkles,
  Calendar,
  Tag,
  AlertCircle,
} from 'lucide-react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from './ui/dialog';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from './ui/alert-dialog';
import { extractMemoriesFromConversation } from '../utils/gemini-service';
import { getActualModel } from '../utils/get-actual-model';

interface MemoryViewerProps {
  personality: Personality;
  messages: Message[];
  config: AIConfig;
  onUpdateMemories: (memories: Memory[]) => void;
}

export function MemoryViewer({ personality, messages, config, onUpdateMemories }: MemoryViewerProps) {
  const memories = personality.memories || [];
  const [editingMemory, setEditingMemory] = useState<Memory | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [selectedTab, setSelectedTab] = useState<'all' | 'chat' | 'core' | 'task'>('all');
  const [showEditDialog, setShowEditDialog] = useState(false);

  // 去重：确保ID唯一，防止重复key警告
  const uniqueMemories = React.useMemo(() => {
    return deduplicateMemories(memories);
  }, [memories]);

  // 按类型筛选记忆
  const filteredMemories = selectedTab === 'all' 
    ? uniqueMemories 
    : uniqueMemories.filter(m => m.type === selectedTab);

  // 按时间倒序排列
  const sortedMemories = [...filteredMemories].sort((a, b) => b.timestamp - a.timestamp);

  // 格式化时间
  const formatTime = (timestamp: number) => {
    const date = new Date(timestamp);
    return date.toLocaleString('zh-CN', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  // 生成新的聊天记忆
  const handleGenerateChatMemory = async () => {
    if (!config.geminiApiKey) {
      toast.error('请先设置Gemini API Key');
      return;
    }

    if (messages.length === 0) {
      toast.error('暂无聊天记录可总结');
      return;
    }

    setIsGenerating(true);
    console.log('🧠 开始生成聊天记忆...');

    let model: string;
    try {
      model = getActualModel(config);
      const memoryResult = await extractMemoriesFromConversation(
        messages,
        config.geminiApiKey,
        model
      );

      if (!memoryResult.memories || memoryResult.memories.length === 0) {
        toast.error('AI未能从对话中提取有价值的记忆');
        setIsGenerating(false);
        return;
      }

      // 将AI提取的记忆转换为统一格式并批量添加
      const generationTimestamp = Date.now();
      const newMemories = memoryResult.memories.map((mem) => ({
        id: generateUniqueMemoryId('ai-memory'),
        personalityId: personality.id,
        type: 'chat' as const,
        content: mem.content,
        memoryType: mem.memoryType,
        importance: mem.importance,
        timestamp: generationTimestamp,
        tags: [...mem.tags, '自动生成', '聊天总结'],
        autoGenerated: true,
        metadata: {
          messageCount: messages.length,
          dateRange: `${formatTime(messages[0].timestamp)} - ${formatTime(messages[messages.length - 1].timestamp)}`,
        },
      }));

      const updatedMemories = [...memories, ...newMemories];
      onUpdateMemories(updatedMemories);
      
      toast.success(`✨ 成功生成 ${newMemories.length} 条聊天记忆！`);
      console.log('✅ 新记忆已添加:', newMemories);
    } catch (error) {
      console.error('❌ 生成记忆失败:', {
        error,
        message: (error as Error).message,
        stack: (error as Error).stack,
        messagesCount: messages.length,
        apiKeySet: !!config.geminiApiKey,
        model
      });
      
      const errorMessage = (error as Error).message || '未知错误';
      if (errorMessage.includes('API key')) {
        toast.error('API密钥错误，请检查Gemini API Key设置');
      } else if (errorMessage.includes('quota')) {
        toast.error('API配额已用完，请检查账户余额');
      } else if (errorMessage.includes('network')) {
        toast.error('网络错误，请检查网络连接');
      } else {
        toast.error(`生成记忆失败：${errorMessage}`);
      }
    } finally {
      setIsGenerating(false);
    }
  };

  // 删除记忆
  const handleDeleteMemory = (memoryId: string) => {
    const updatedMemories = memories.filter(m => m.id !== memoryId);
    onUpdateMemories(updatedMemories);
    toast.success('记忆已删除');
    console.log('🗑️ 删除记忆:', memoryId);
  };

  // 开始编辑记忆
  const handleEditMemory = (memory: Memory) => {
    setEditingMemory({ ...memory });
    setShowEditDialog(true);
  };

  // 保存编辑
  const handleSaveEdit = () => {
    if (!editingMemory) return;

    const updatedMemories = memories.map(m => 
      m.id === editingMemory.id ? editingMemory : m
    );
    onUpdateMemories(updatedMemories);
    setShowEditDialog(false);
    setEditingMemory(null);
    toast.success('记忆已更新');
    console.log('💾 更新记忆:', editingMemory.id);
  };

  // 添加新记忆
  const handleAddMemory = () => {
    const timestamp = Date.now();
    const newMemory: Memory = {
      id: generateUniqueMemoryId('memory'),
      personalityId: personality.id,
      type: 'core',
      content: '',
      memoryType: 'long-term',
      importance: 'medium',
      timestamp: timestamp,
      tags: [],
      autoGenerated: false,
    };
    setEditingMemory(newMemory);
    setShowEditDialog(true);
  };

  // 获取记忆类型标签
  const getTypeIcon = (type: string) => {
    switch (type) {
      case 'chat':
        return <MessageSquare className="w-4 h-4" />;
      case 'core':
        return <Brain className="w-4 h-4" />;
      case 'task':
        return <Clock className="w-4 h-4" />;
      default:
        return <Brain className="w-4 h-4" />;
    }
  };

  const getTypeName = (type: string) => {
    switch (type) {
      case 'chat':
        return '聊天记忆';
      case 'core':
        return '核心记忆';
      case 'task':
        return '任务记忆';
      default:
        return '未知';
    }
  };

  const getTypeColor = (type: string) => {
    switch (type) {
      case 'chat':
        return 'bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/20';
      case 'core':
        return 'bg-purple-500/10 text-purple-600 dark:text-purple-400 border-purple-500/20';
      case 'task':
        return 'bg-orange-500/10 text-orange-600 dark:text-orange-400 border-orange-500/20';
      default:
        return 'bg-gray-500/10 text-gray-600 dark:text-gray-400 border-gray-500/20';
    }
  };

  const getImportanceColor = (importance: string) => {
    switch (importance) {
      case 'high':
        return 'bg-red-500/10 text-red-600 dark:text-red-400 border-red-500/20';
      case 'medium':
        return 'bg-yellow-500/10 text-yellow-600 dark:text-yellow-400 border-yellow-500/20';
      case 'low':
        return 'bg-green-500/10 text-green-600 dark:text-green-400 border-green-500/20';
      default:
        return 'bg-gray-500/10 text-gray-600 dark:text-gray-400 border-gray-500/20';
    }
  };

  return (
    <div className="h-full flex flex-col">
      {/* 头部 */}
      <div className="flex-shrink-0 p-3 md:p-4 border-b space-y-3 md:space-y-4">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-3">
          <div className="flex-1 min-w-0">
            <h2 className="flex items-center gap-2">
              <Brain className="w-5 h-5 flex-shrink-0" />
              <span className="truncate">{personality.name} 的记忆库</span>
            </h2>
            <p className="text-sm text-muted-foreground mt-1">
              共 {memories.length} 条记忆 | 
              长期 {memories.filter(m => m.memoryType === 'long-term').length} 条 • 
              短期 {memories.filter(m => m.memoryType === 'short-term').length} 条
            </p>
            <p className="text-xs text-muted-foreground mt-0.5 hidden md:block">
              每5条消息AI自动总结 | 长时记忆永久保存 | 短时记忆7天或30条后清理
            </p>
          </div>
          <div className="flex gap-2 flex-shrink-0">
            <Button
              onClick={handleGenerateChatMemory}
              disabled={isGenerating || !config.geminiApiKey}
              size="sm"
              className="touch-manipulation min-h-[40px] md:min-h-[36px]"
            >
              {isGenerating ? (
                <>
                  <Sparkles className="w-4 h-4 mr-2 animate-spin" />
                  <span className="hidden sm:inline">生成中...</span>
                  <span className="sm:hidden">...</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 md:mr-2" />
                  <span className="hidden md:inline">总结新记忆</span>
                </>
              )}
            </Button>
            <Button 
              onClick={handleAddMemory} 
              size="sm" 
              variant="outline"
              className="touch-manipulation min-h-[40px] md:min-h-[36px]"
            >
              <Plus className="w-4 h-4 md:mr-2" />
              <span className="hidden md:inline">添加记忆</span>
            </Button>
          </div>
        </div>

        {/* 筛选标签 */}
        <Tabs value={selectedTab} onValueChange={(v) => setSelectedTab(v as any)}>
          <TabsList className="grid w-full grid-cols-4 h-auto">
            <TabsTrigger value="all" className="touch-manipulation min-h-[44px] md:min-h-[36px] text-xs md:text-sm">
              <span className="hidden sm:inline">全部 ({memories.length})</span>
              <span className="sm:hidden">全部</span>
            </TabsTrigger>
            <TabsTrigger value="chat" className="touch-manipulation min-h-[44px] md:min-h-[36px] text-xs md:text-sm">
              <MessageSquare className="w-4 h-4 md:mr-1 flex-shrink-0" />
              <span className="hidden sm:inline ml-1">聊天 ({memories.filter(m => m.type === 'chat').length})</span>
              <span className="sm:hidden ml-1">聊天</span>
            </TabsTrigger>
            <TabsTrigger value="core" className="touch-manipulation min-h-[44px] md:min-h-[36px] text-xs md:text-sm">
              <Brain className="w-4 h-4 md:mr-1 flex-shrink-0" />
              <span className="hidden sm:inline ml-1">核心 ({memories.filter(m => m.type === 'core').length})</span>
              <span className="sm:hidden ml-1">核心</span>
            </TabsTrigger>
            <TabsTrigger value="task" className="touch-manipulation min-h-[44px] md:min-h-[36px] text-xs md:text-sm">
              <Clock className="w-4 h-4 md:mr-1 flex-shrink-0" />
              <span className="hidden sm:inline ml-1">任务 ({memories.filter(m => m.type === 'task').length})</span>
              <span className="sm:hidden ml-1">任务</span>
            </TabsTrigger>
          </TabsList>
        </Tabs>
      </div>

      {/* 记忆列表 */}
      <div className="flex-1 overflow-y-auto">
        <div className="p-3 md:p-4 space-y-3">
          {sortedMemories.length === 0 ? (
            <Card className="p-8 md:p-12">
              <div className="flex flex-col items-center text-center text-muted-foreground">
                <Brain className="w-12 h-12 md:w-16 md:h-16 mb-4 opacity-50" />
                <p className="mb-2">暂无{selectedTab === 'all' ? '' : getTypeName(selectedTab)}</p>
                <p className="text-sm">
                  {selectedTab === 'chat' && '点击"总结新记忆"让AI自动生成聊天记忆'}
                  {selectedTab === 'core' && '点击"添加记忆"手动创建核心记忆'}
                  {selectedTab === 'task' && '点击"添加记忆"创建任务提醒'}
                  {selectedTab === 'all' && '点击上方按钮开始创建记忆'}
                </p>
              </div>
            </Card>
          ) : (
            sortedMemories.map((memory, index) => (
              <Card key={`${memory.id}-${index}`} className="p-3 md:p-4 active:shadow-lg transition-shadow">
                <div className="space-y-3">
                  {/* 头部：类型、重要性、时间 */}
                  <div className="flex items-start justify-between gap-2">
                    <div className="flex flex-wrap gap-2 flex-1 min-w-0">
                      <Badge variant="outline" className={`${getTypeColor(memory.type)} text-xs`}>
                        {getTypeIcon(memory.type)}
                        <span className="ml-1">{getTypeName(memory.type)}</span>
                      </Badge>
                      <Badge variant="outline" className={`${getImportanceColor(memory.importance)} text-xs`}>
                        {memory.importance === 'high' && '⭐ 高'}
                        {memory.importance === 'medium' && '⚡ 中'}
                        {memory.importance === 'low' && '💡 低'}
                      </Badge>
                      {memory.autoGenerated && (
                        <Badge variant="outline" className="bg-green-500/10 text-green-600 dark:text-green-400 border-green-500/20 text-xs">
                          <Sparkles className="w-3 h-3 mr-1" />
                          AI生成
                        </Badge>
                      )}
                    </div>
                    <div className="flex gap-1 flex-shrink-0">
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-10 w-10 md:h-8 md:w-8 touch-manipulation"
                        onClick={() => handleEditMemory(memory)}
                      >
                        <Edit className="w-4 h-4" />
                      </Button>
                      <AlertDialog>
                        <AlertDialogTrigger asChild>
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-10 w-10 md:h-8 md:w-8 text-red-500 hover:text-red-600 hover:bg-red-500/10 touch-manipulation"
                          >
                            <Trash2 className="w-4 h-4" />
                          </Button>
                        </AlertDialogTrigger>
                        <AlertDialogContent className="w-[90vw] max-w-md">
                          <AlertDialogHeader>
                            <AlertDialogTitle>确认删除记忆？</AlertDialogTitle>
                            <AlertDialogDescription>
                              此操作将永久删除这条记忆，无法恢复。
                            </AlertDialogDescription>
                          </AlertDialogHeader>
                          <AlertDialogFooter className="flex-col sm:flex-row gap-2">
                            <AlertDialogCancel className="touch-manipulation min-h-[44px]">取消</AlertDialogCancel>
                            <AlertDialogAction
                              onClick={() => handleDeleteMemory(memory.id)}
                              className="bg-red-500 hover:bg-red-600 touch-manipulation min-h-[44px]"
                            >
                              确认删除
                            </AlertDialogAction>
                          </AlertDialogFooter>
                        </AlertDialogContent>
                      </AlertDialog>
                    </div>
                  </div>

                  {/* 内容 */}
                  <div className="prose prose-sm dark:prose-invert max-w-none">
                    <p className="whitespace-pre-wrap text-sm leading-relaxed select-text">
                      {memory.content}
                    </p>
                  </div>

                  {/* 元数据 */}
                  <div className="flex flex-wrap gap-2 md:gap-3 text-xs text-muted-foreground">
                    <div className="flex items-center gap-1">
                      <Calendar className="w-3 h-3 flex-shrink-0" />
                      <span className="truncate">{formatTime(memory.timestamp)}</span>
                    </div>
                    {memory.metadata?.messageCount && (
                      <div className="flex items-center gap-1">
                        <MessageSquare className="w-3 h-3 flex-shrink-0" />
                        <span>总结了 {memory.metadata.messageCount} 条消息</span>
                      </div>
                    )}
                    {memory.metadata?.dateRange && (
                      <div className="flex items-center gap-1 hidden md:flex">
                        <Clock className="w-3 h-3 flex-shrink-0" />
                        <span>{memory.metadata.dateRange}</span>
                      </div>
                    )}
                    {memory.tags.length > 0 && (
                      <div className="flex items-center gap-1 w-full md:w-auto">
                        <Tag className="w-3 h-3 flex-shrink-0" />
                        <span className="truncate">{memory.tags.join(', ')}</span>
                      </div>
                    )}
                  </div>
                </div>
              </Card>
            ))
          )}
        </div>
      </div>

      {/* 编辑对话框 */}
      <Dialog open={showEditDialog} onOpenChange={setShowEditDialog}>
        <DialogContent className="max-w-2xl max-h-[80vh] flex flex-col" aria-describedby="edit-memory-description">
          <DialogHeader>
            <DialogTitle>
              {editingMemory?.id && memories.find(m => m.id === editingMemory.id) 
                ? '编辑记忆' 
                : '添加新记忆'}
            </DialogTitle>
            <DialogDescription id="edit-memory-description">
              编辑 {personality.name} 的记忆内容
            </DialogDescription>
          </DialogHeader>

          {editingMemory && (
            <div className="space-y-4 flex-1 overflow-y-auto">
              {/* 记忆类型 */}
              <div className="space-y-2">
                <Label>记忆类型</Label>
                <div className="flex gap-2">
                  <Button
                    variant={editingMemory.type === 'chat' ? 'default' : 'outline'}
                    size="sm"
                    onClick={() => setEditingMemory({ ...editingMemory, type: 'chat' })}
                  >
                    <MessageSquare className="w-4 h-4 mr-1" />
                    聊天记忆
                  </Button>
                  <Button
                    variant={editingMemory.type === 'core' ? 'default' : 'outline'}
                    size="sm"
                    onClick={() => setEditingMemory({ ...editingMemory, type: 'core' })}
                  >
                    <Brain className="w-4 h-4 mr-1" />
                    核心记忆
                  </Button>
                  <Button
                    variant={editingMemory.type === 'task' ? 'default' : 'outline'}
                    size="sm"
                    onClick={() => setEditingMemory({ ...editingMemory, type: 'task' })}
                  >
                    <Clock className="w-4 h-4 mr-1" />
                    任务记忆
                  </Button>
                </div>
              </div>

              {/* 重要性 */}
              <div className="space-y-2">
                <Label>重要性</Label>
                <div className="flex gap-2">
                  <Button
                    variant={editingMemory.importance === 'high' ? 'default' : 'outline'}
                    size="sm"
                    onClick={() => setEditingMemory({ ...editingMemory, importance: 'high' })}
                  >
                    ⭐ 高
                  </Button>
                  <Button
                    variant={editingMemory.importance === 'medium' ? 'default' : 'outline'}
                    size="sm"
                    onClick={() => setEditingMemory({ ...editingMemory, importance: 'medium' })}
                  >
                    ⚡ 中
                  </Button>
                  <Button
                    variant={editingMemory.importance === 'low' ? 'default' : 'outline'}
                    size="sm"
                    onClick={() => setEditingMemory({ ...editingMemory, importance: 'low' })}
                  >
                    💡 低
                  </Button>
                </div>
              </div>

              {/* 记忆内容 */}
              <div className="space-y-2">
                <Label>记忆内容</Label>
                <Textarea
                  value={editingMemory.content}
                  onChange={(e) => setEditingMemory({ ...editingMemory, content: e.target.value })}
                  placeholder="输入记忆内容..."
                  className="min-h-[200px]"
                />
              </div>

              {/* 标签 */}
              <div className="space-y-2">
                <Label>标签（用逗号分隔）</Label>
                <Input
                  value={editingMemory.tags.join(', ')}
                  onChange={(e) => setEditingMemory({ 
                    ...editingMemory, 
                    tags: e.target.value.split(',').map(t => t.trim()).filter(Boolean)
                  })}
                  placeholder="例如：重要, 约定, 喜好"
                />
              </div>

              {/* 任务相关（仅任务记忆显示） */}
              {editingMemory.type === 'task' && (
                <div className="space-y-2">
                  <Label>任务时间</Label>
                  <Input
                    type="datetime-local"
                    value={editingMemory.metadata?.taskTime || ''}
                    onChange={(e) => setEditingMemory({ 
                      ...editingMemory, 
                      metadata: { ...editingMemory.metadata, taskTime: e.target.value }
                    })}
                  />
                </div>
              )}
            </div>
          )}

          <div className="flex justify-end gap-2 flex-shrink-0 border-t pt-4">
            <Button variant="outline" onClick={() => setShowEditDialog(false)}>
              <X className="w-4 h-4 mr-2" />
              取消
            </Button>
            <Button onClick={handleSaveEdit}>
              <Save className="w-4 h-4 mr-2" />
              保存
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
