// 记忆清理工具
// 自动清理过期的短期记忆，保留所有长期记忆

import { Memory, Personality } from '../App';

// 短期记忆配置
export const SHORT_TERM_MEMORY_CONFIG = {
  MAX_DAYS: 7, // 短期记忆最多保留7天
  MAX_COUNT: 30, // 最多保留30条短期记忆
};

/**
 * 清理单个角色的过期短期记忆
 * @param memories 记忆列表
 * @returns 清理后的记忆列表和被移除的记忆数量
 */
export function cleanShortTermMemories(memories: Memory[]): {
  cleaned: Memory[];
  removedCount: number;
} {
  if (!memories || memories.length === 0) {
    return { cleaned: [], removedCount: 0 };
  }

  const now = Date.now();
  const maxAge = SHORT_TERM_MEMORY_CONFIG.MAX_DAYS * 24 * 60 * 60 * 1000;

  // 分离长期和短期记忆
  const longTermMemories = memories.filter(m => m.memoryType === 'long-term');
  const shortTermMemories = memories
    .filter(m => m.memoryType === 'short-term')
    .filter(m => (now - m.timestamp) < maxAge) // 移除超过指定天数的短期记忆
    .sort((a, b) => b.timestamp - a.timestamp) // 按时间倒序
    .slice(0, SHORT_TERM_MEMORY_CONFIG.MAX_COUNT); // 只保留最近N条

  const cleaned = [...longTermMemories, ...shortTermMemories];
  const removedCount = memories.length - cleaned.length;

  return { cleaned, removedCount };
}

/**
 * 清理所有角色的过期短期记忆
 * @param personalities 角色列表
 * @returns 清理后的角色列表和总移除数量
 */
export function cleanAllShortTermMemories(personalities: Personality[]): {
  cleaned: Personality[];
  totalRemovedCount: number;
  details: Array<{ personalityId: string; personalityName: string; removedCount: number }>;
} {
  if (!personalities || personalities.length === 0) {
    return { cleaned: [], totalRemovedCount: 0, details: [] };
  }

  let totalRemovedCount = 0;
  const details: Array<{ personalityId: string; personalityName: string; removedCount: number }> = [];

  const cleaned = personalities.map(p => {
    if (!p.memories || p.memories.length === 0) {
      return p;
    }

    const { cleaned: cleanedMemories, removedCount } = cleanShortTermMemories(p.memories);

    if (removedCount > 0) {
      totalRemovedCount += removedCount;
      details.push({
        personalityId: p.id,
        personalityName: p.name,
        removedCount,
      });
    }

    return { ...p, memories: cleanedMemories };
  });

  return { cleaned, totalRemovedCount, details };
}

/**
 * 获取记忆统计信息
 * @param memories 记忆列表
 */
export function getMemoryStats(memories: Memory[]) {
  if (!memories || memories.length === 0) {
    return {
      total: 0,
      longTerm: 0,
      shortTerm: 0,
      autoGenerated: 0,
      manual: 0,
    };
  }

  const longTerm = memories.filter(m => m.memoryType === 'long-term').length;
  const shortTerm = memories.filter(m => m.memoryType === 'short-term').length;
  const autoGenerated = memories.filter(m => m.autoGenerated).length;
  const manual = memories.length - autoGenerated;

  return {
    total: memories.length,
    longTerm,
    shortTerm,
    autoGenerated,
    manual,
  };
}

/**
 * 获取即将过期的短期记忆（3天内过期）
 * @param memories 记忆列表
 */
export function getExpiringShortTermMemories(memories: Memory[]): Memory[] {
  if (!memories || memories.length === 0) {
    return [];
  }

  const now = Date.now();
  const threeDays = 3 * 24 * 60 * 60 * 1000;
  const maxAge = SHORT_TERM_MEMORY_CONFIG.MAX_DAYS * 24 * 60 * 60 * 1000;
  const expiringThreshold = maxAge - threeDays;

  return memories
    .filter(m => m.memoryType === 'short-term')
    .filter(m => {
      const age = now - m.timestamp;
      return age >= expiringThreshold && age < maxAge;
    })
    .sort((a, b) => a.timestamp - b.timestamp); // 按时间正序，最早的在前
}

/**
 * 判断是否需要清理记忆
 * @param memories 记忆列表
 */
export function needsMemoryCleanup(memories: Memory[]): boolean {
  if (!memories || memories.length === 0) {
    return false;
  }

  const { cleaned, removedCount } = cleanShortTermMemories(memories);
  return removedCount > 0;
}
